djangodelights/djangodelights/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("inventory.urls")),
]

djangodelights/inventory/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
   path('', views.home, name="home"),
   path("accounts/", include("django.contrib.auth.urls"), name="login"),
   path("logout/", views.logout_view, name="logout"),
   path('ingredients/', views.IngredientsList.as_view(), name='ingredientslist'),
   path('menuitem/', views.MenusList.as_view(), name="menuslist"),
   path('purchases/', views.PurchasesList.as_view(), name="purchaseslist"),
   path('reports/', views.reports, name="reports"),
   path('receipes/', views.ReceipesList.as_view(), name="receiperequirements"),
   path("ingredients/delete/<pk>", views.IngredientDelete.as_view(), name="ingredientdelete"),
   path("menuitem/create", views.AddMenuItemCreate.as_view(), name="menuitemcreate"),
   path("ingredient/create", views.AddIngredientCreate.as_view(), name="ingredientcreate"),
   path("ingredient/update/<pk>", views.IngredientUpdate.as_view(), name="ingredientupdate"),
   path("receipe/create", views.AddReceipeCreate.as_view(), name="receipecreate"),
   path("purchase/create", views.AddPurchaseCreate.as_view(), name="purchasecreate"),
   path('sales-report/', views.sales_report, name='sales_report'),
]

djangodelights/inventory/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=200)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  
    unit_price = models.IntegerField(default=0)

    GRAM = "g"
    KILOGRAM = "kg"
    LITER = "l"
    MILLILITER = "ml"
    TEASPOON = "tsp"
    TABLESPOON = "tbsp"
    CUP = "cup"
    PIECE = "pc"
    PINCH = "pinch"

    KITCHEN_UNIT_CHOICES = [
        (GRAM, "Gram"),
        (KILOGRAM, "Kilogram"),
        (LITER, "Liter"),
        (MILLILITER, "Milliliter"),
        (TEASPOON, "Teaspoon"),
        (TABLESPOON, "Tablespoon"),
        (CUP, "Cup"),
        (PIECE, "Piece"),
        (PINCH, "Pinch"),
    ]

    unit = models.CharField(max_length=5, choices=KITCHEN_UNIT_CHOICES, default = GRAM)

    def __str__(self):
        return self.name 
    # + ", " + self.quantity + ", " + self.unit+ ", " + self.unit_price

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("ingredientcreate") 

class MenuItem(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  

    def __str__(self):
        return self.title 
    class Meta:
        ordering = ["title"]   
    def get_absolute_url(self):
        return reverse("menuitemcreate") 
    
    def calculate_cost(self):
        total_cost = 0
        for req in self.receiperequirement_set.all():
            total_cost += req.quantity * req.ingredient.unit_price
        return total_cost

    def calculate_profit(self):
        cost = self.calculate_cost()
        return self.price - cost


class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Purchase of {self.menu_item} on {self.date.strftime('%Y-%m-%d %H:%M:%S')}"
    
    def calculate_cost(self):
        return self.menu_item.calculate_cost()

    def calculate_revenue(self):
        return self.menu_item.price

    def calculate_profit(self):
        return self.calculate_revenue() - self.calculate_cost()



class ReceipeRequirement(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  

    def __str__(self):
        return f"{self.menu_item} - {self.ingredient} (Qty: {self.quantity})"
    class Meta:
        ordering = ["menu_item"]
    def get_absolute_url(self):
        return reverse("receipecreate") 
    

djangodelights/inventory/forms.py
from django import forms
from .models import Ingredient, MenuItem, ReceipeRequirement, Purchase

class AddMenuItem(forms.ModelForm):
  class Meta:
    model = MenuItem
    fields = ("__all__")

class AddIngredient(forms.ModelForm):
  class Meta:
    model = Ingredient
    fields = ("__all__")

class AddReceipe(forms.ModelForm):
  class Meta:
    model = ReceipeRequirement
    fields = ("__all__")

class AddPurchase(forms.ModelForm):
  class Meta:
    model = Purchase
    fields = ("__all__")

class IngredientUpdateForm(forms.ModelForm):
  class Meta:
    model = Ingredient
    fields = ['quantity']

djangodelights/inventory/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DeleteView
from .models import Ingredient, MenuItem, ReceipeRequirement, Purchase
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from .forms import AddMenuItem, AddIngredient, AddReceipe, AddPurchase, IngredientUpdateForm

#Login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout

def logout_view(request):
  logout(request)
  return redirect("home")

@login_required
def home(request):
  return render(request, "inventory/home.html")

@login_required
def reports(request):
  return render(request, "inventory/reports.html")

@login_required
def receiperequirements(request):
  return render(request, "inventory/receipes.html")

class IngredientsList(LoginRequiredMixin,ListView):
  model = Ingredient
  template_name = "inventory/ingredients.html"

class MenusList(LoginRequiredMixin, ListView):
  model = MenuItem
  template_name = "inventory/menus.html"

class IngredientUpdate(LoginRequiredMixin, UpdateView):
  model = Ingredient
  template_name = "inventory/ingredient_update_form.html"
  form_class = IngredientUpdateForm
  success_url = reverse_lazy('ingredientslist')

class IngredientDelete(LoginRequiredMixin, DeleteView):
  model = Ingredient
  template_name = "inventory/ingredient_delete_form.html"
  success_url = reverse_lazy('ingredientslist')

class PurchasesList(LoginRequiredMixin, ListView):
  model = Purchase
  template_name = "inventory/purchases.html"

class ReceipesList(LoginRequiredMixin, ListView):
  model = ReceipeRequirement
  template_name = "inventory/receipes.html"

class AddMenuItemCreate(LoginRequiredMixin, CreateView):
  model = MenuItem
  template_name = "inventory/add_menu_item.html"
  form_class = AddMenuItem

class AddIngredientCreate(LoginRequiredMixin, CreateView):
  model = Ingredient
  template_name = "inventory/add_menu_item.html"
  form_class = AddIngredient

class AddReceipeCreate(LoginRequiredMixin, CreateView):
  model = ReceipeRequirement
  template_name = "inventory/add_receipe.html"
  form_class = AddReceipe

class AddPurchaseCreate(LoginRequiredMixin, CreateView):
  model = Purchase
  template_name = "inventory/add_purchase.html"
  form_class = AddPurchase
  success_url = reverse_lazy('purchaseslist')

@login_required
def sales_report(request):
    purchases = Purchase.objects.all()

    total_revenue = 0
    total_profit = 0
    total_cost = 0

    sales_data = []
    for purchase in purchases:
        item = purchase.menu_item
        cost = purchase.calculate_cost()
        revenue = purchase.calculate_revenue()
        profit = purchase.calculate_profit()

        sales_data.append({
            'title': item.title,
            'cost': cost,
            'price': item.price,
            'profit': profit,
        })

        total_revenue += revenue
        total_profit += profit
        total_cost  += cost

    return render(request, 'inventory/sales_report.html', {
        'sales_data': sales_data,
        'total_cost': total_cost,
        'total_revenue': total_revenue,
        'total_profit': total_profit
    })

djangodelights/inventory/templates/inventory/add_ingredient.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" />
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_menu_item.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" />
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_purchase.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" />
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_receipe.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" />
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/base.html
<!DOCTYPE html>
<html lang="en">
<head>       
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Delight - hello!</title>
    {% block head %} 

    {% endblock %}
</head>
<body>
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <br>
    <a href="{% url 'home' %}">HOME</a>
    <h1>Michelin *** Star Restaurant</h1>
    <h1>Management Console</h1>

    {% block content %}


    {% endblock %}

</body>
</html>

djangodelights/inventory/templates/inventory/home.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}

<div class="center-content">
    <p>Welcome!</p>
    <p>What changes would you like to register today?</p>
    <p>Would you like to inspect the profit / revenue report?</p>
    <div class="button-container">
        <a href="{% url 'menuslist' %}" class="button">Menus</a>
        <a href="{% url 'ingredientslist' %}" class="button">Ingredients</a>
        <a href="{% url 'purchaseslist' %}" class="button">Purchases</a>
        {% comment %}
        <a href="{% url 'receiperequirements' %}" class="button">Receipes</a>
        {% endcomment %}
        <a href="{% url 'sales_report' %}" class="button">Reports</a>
    </div>

{% endblock %}

djangodelights/inventory/templates/inventory/ingredient_delete_form.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<h2>Delete Ingredient</h2>
<form method="post">
<div>
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object.name }}"?</p>
  <input type="submit" value="Confirm" />
</div>
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/ingredient_update_form.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<h2>Update Ingredient</h2>
<form method="post">
<div>
  {% csrf_token %}
  {{ form.as_p }}
  <p>Are you sure you want to update "{{ object.name }}"?</p>
  <input type="submit" value="Confirm" />
</div>
</form>
{% endblock %}

djangodelights/inventory/templates/inventory/ingredients.html
{% extends "inventory/base.html" %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'inventory/style.css' %}" />
{% endblock %} 

{% block content %}
<h2>Ingredients</h2>
<a href="{% url 'ingredientslist' %}"></a>
<table id="Ingredients">
  <tr>
    <th>Ingredient</th>
    <th>Quantity</th>
    <th>Unit</th>
    <th>Unit Price</th>

    <th>Edit</th>

    <th>Delete</th>
  </tr>

  {% for ingredient in ingredient_list %}

  <tr>
    <td>{{ ingredient.name }}</td>
    <td>{{ ingredient.quantity }}</td>
    <td>{{ ingredient.unit }}</td>
    <td>{{ ingredient.unit_price }}</td>

    <td><a href="{% url 'ingredientupdate' ingredient.id %}">Edit</a></td>

    <td><a href="{% url 'ingredientdelete' ingredient.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<a href="{% url 'ingredientcreate'%}"><button class="btn">Add Ingredient</button></a>

{% endblock %}

djangodelights/inventory/templates/inventory/menus.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<h2>Menus</h2>
<table id="Menus">
    <tr>
        <th>Dish</th>
        <th>Price</th>
        <th>Ingredients</th>
    </tr>
    {% for menu in menuitem_list %}
    <tr>
        <td>{{ menu.title }}</td>
        <td>{{ menu.price }}</td>
        <td>
            {% for req in menu.receiperequirement_set.all %}
                {{ req.ingredient.name }} ({{ req.quantity }} {{ req.ingredient.unit }})<br>
            {% empty %}
                No ingredients.
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'menuitemcreate'%}"><button class="btn">Add Menu Item</button></a> 
<a href="{% url 'receipecreate'%}"><button class="btn">Add Ingredient to Receipe</button></a>

{% endblock %}

djangodelights/inventory/templates/inventory/purchases.html
{% extends "inventory/base.html" %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'inventory/style.css' %}" />
{% endblock %} 

{% block content %}
<h2>Purchases</h2>
<a href="{% url 'purchaseslist' %}"></a>
<table id="Purchases">
  <tr>
    <th>Menu Item</th>
    <th>Date</th>
    <th>Price</th>
  </tr>

  {% for purchase in purchase_list %}

  <tr>
    <td>{{ purchase.menu_item }}</td>
    <td>{{ purchase.date }}</td>
    <td>{{ purchase.menu_item.price }}</td>
  </tr>
  {% endfor %}
</table>

<a href="{% url 'purchasecreate'%}"><button class="btn">Record Purchase</button></a>

{% endblock %}

djangodelights/inventory/templates/inventory/receipes.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<h2>Receipes</h2>
<table id="Menus">
    <tr>
        <th>Menu item</th>
        <th>Ingredients</th>
        <th>Quantity</th>
        <th>Unit</th>
    </tr>
    {% for receipe in receiperequirement_list %}
    <tr>
        <td>{{ receipe.menu_item }}</td>
        <td>{{ receipe.ingredient }}</td>
        <td>{{ receipe.quantity }}</td>
        <td>{{ receipe.ingredient.unit }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'receipecreate'%}"><button class="btn">Add Ingredient to Receipe</button></a>

{% endblock %}

djangodelights/inventory/templates/inventory/reports.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}    
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}

<p>Reports</p>

{% endblock %}

djangodelights/inventory/templates/inventory/sales_report.html
{% extends "inventory/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'inventory/style.css' %}">
{% endblock %}

{% block content %}
<h2>Sales Report</h2>
<table id="SalesReport">
    <tr>
        <th>Dish</th>
        <th>Cost</th>
        <th>Price</th>
        <th>Profit</th>
    </tr>
    {% for sale in sales_data %}
    <tr>
        <td>{{ sale.title }}</td>
        <td>{{ sale.cost|floatformat:2 }}</td>
        <td>{{ sale.price|floatformat:2 }}</td>
        <td>{{ sale.profit|floatformat:2 }}</td>
    </tr>
    {% endfor %}
</table>

<h3>Total Revenue: {{ total_revenue|floatformat:2 }}</h3>
<h3>Total Cost: {{ total_cost|floatformat:2 }}</h3>
<h3>Total Profit: {{ total_profit|floatformat:2 }}</h3>
{% endblock %}